package org.meb.oneringdb.db.model;

public enum CardType {

	HERO, ALLY, ATTACHMENT, EVENT, QUEST, TREACHERY, ENEMY, LOCATION, OBJECTIVE, TREASURE, CAMPAIGN,
	PLAYER_SIDE_QUEST, ENCOUNTER_SIDE_QUEST, SHIP_ENEMY, SHIP_OBJECTIVE, GENCON_SETUP,
	NIGHTMARE_SETUP
}